// <auto-generated />
using DoAn_Pc_DACS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_Pc_DACS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_Pc_DACS.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 99,
                            Name = "PC GAMING",
                            Slug = "pc-gaming"
                        },
                        new
                        {
                            Id = 100,
                            Name = "PC WORKSTATION",
                            Slug = "pc-workstation"
                        });
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.ComponentSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cooler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolerBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoolerSl")
                        .HasColumnType("int");

                    b.Property<string>("FormFactor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFactorBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormFactorSl")
                        .HasColumnType("int");

                    b.Property<string>("Mainboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainboardBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MainboardSl")
                        .HasColumnType("int");

                    b.Property<string>("PowerSupply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSupplyBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerSupplySl")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RamBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamSl")
                        .HasColumnType("int");

                    b.Property<string>("RamType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Socket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocketBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SocketSl")
                        .HasColumnType("int");

                    b.Property<string>("Storage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageSl")
                        .HasColumnType("int");

                    b.Property<string>("Vga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VgaBh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VgaSl")
                        .HasColumnType("int");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ComponentSpecs");

                    b.HasData(
                        new
                        {
                            Id = 99,
                            CoolerBh = "12 Tháng",
                            CoolerSl = 1,
                            FormFactor = "Micro-ATX",
                            FormFactorBh = "12 Tháng",
                            FormFactorSl = 1,
                            MainboardBh = "36 Tháng",
                            MainboardSl = 1,
                            PowerSupplyBh = "36 Tháng",
                            PowerSupplySl = 1,
                            ProductId = 99,
                            RamBh = "36 Tháng",
                            RamSl = 1,
                            RamType = "16GB (2x8GB) DDR4 3200MHz",
                            Socket = "Intel LGA 1700",
                            SocketBh = "36 Tháng",
                            SocketSl = 1,
                            StorageBh = "36 Tháng",
                            StorageSl = 1,
                            VgaBh = "36 Tháng",
                            VgaSl = 1,
                            Wattage = 650
                        },
                        new
                        {
                            Id = 100,
                            CoolerBh = "12 Tháng",
                            CoolerSl = 1,
                            FormFactor = "ATX",
                            FormFactorBh = "12 Tháng",
                            FormFactorSl = 1,
                            MainboardBh = "36 Tháng",
                            MainboardSl = 1,
                            PowerSupplyBh = "36 Tháng",
                            PowerSupplySl = 1,
                            ProductId = 100,
                            RamBh = "36 Tháng",
                            RamSl = 1,
                            RamType = "32GB (2x16GB) DDR5 6000MHz RGB",
                            Socket = "Intel LGA 1700 (Core Ultra)",
                            SocketBh = "36 Tháng",
                            SocketSl = 1,
                            StorageBh = "36 Tháng",
                            StorageSl = 1,
                            VgaBh = "36 Tháng",
                            VgaSl = 1,
                            Wattage = 850
                        });
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 99,
                            CategoryId = 99,
                            Discount = 3,
                            ImageUrl = "https://placehold.co/600x600?text=PC+GAMING+1",
                            Name = "PC TTG GAMING i5 12400F - RTX 5060",
                            OldPrice = 29990000m,
                            Price = 28980000m
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 99,
                            Discount = 4,
                            ImageUrl = "https://placehold.co/600x600?text=PC+GAMING+2",
                            Name = "PC TTG GAMING ULTRA 5 245KF",
                            OldPrice = 39990000m,
                            Price = 38480000m
                        });
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.ComponentSpec", b =>
                {
                    b.HasOne("DoAn_Pc_DACS.Models.Product", "Product")
                        .WithOne("ComponentSpec")
                        .HasForeignKey("DoAn_Pc_DACS.Models.ComponentSpec", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.Product", b =>
                {
                    b.HasOne("DoAn_Pc_DACS.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.ProductImage", b =>
                {
                    b.HasOne("DoAn_Pc_DACS.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DoAn_Pc_DACS.Models.Product", b =>
                {
                    b.Navigation("ComponentSpec")
                        .IsRequired();

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
